[package]
name = "slideshowgodockerrustsetup"
version = "0.1.0"
edition = "2024"

[dependencies]

rayon = "1.10"
rusqlite = { version = "0.31", features = ["bundled"] }
image = "0.25"
walkdir = "2.5"
